inherit_from: .rubocop_todo.yml

Layout/IndentationWidth:
  Width: 4

Metrics/BlockLength:
  Max: 32

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
