# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
    gradle_file = "app/build.gradle.kts"

    desc "Runs all the tests"
    lane :test do
        gradle(task: "test")
    end

    desc "Updates app version"
    lane :version do |options|
        version_name = options.fetch(:name, "")
        if version_name != ""
            android_set_version_name(
                version_name: version_name,
                gradle_file: gradle_file
            )
        end

        if options.fetch(:increment, true)
            android_set_version_code(gradle_file: gradle_file)
        end
    end

    desc "Build release app bundle"
    lane :bundle do
        gradle(task: "clean bundleRelease")
    end

    desc "Deploy a new version to the Google Play"
    lane :deploy do |options|
        version(name: options[:version])
        bundle

        version_name = android_get_version_name(gradle_file: gradle_file)

        upload_to_play_store(
            aab: "app/release/app-release.aab",
            version_name: "Artemis Agent #{version_name}",
            track: options.fetch(:track, "production"),
            priority: options.fetch(:priority, 0)
        )
    end
end
