package com.walkertribe.ian.iface

import com.walkertribe.ian.enums.Origin
import com.walkertribe.ian.protocol.ArtemisPacket
import com.walkertribe.ian.protocol.ArtemisPacketException
import com.walkertribe.ian.protocol.RawPacket
import com.walkertribe.ian.protocol.core.world.ObjectUpdatePacket
import io.ktor.utils.io.core.ByteReadPacket
import io.ktor.utils.io.core.readBytes

/**
 * Object which reports the results of a packet parsing attempt.
 * @author rjwut
 */
sealed class ParseResult(
    /**
     * Returns the packet object generated by the parse attempt.
     */
    val packet: ArtemisPacket
) : DispatchEvent {
    internal class Processing(origin: Origin, type: Int, payload: ByteReadPacket) :
        ParseResult(RawPacket.Unparsed(origin, type, payload.copy().readBytes()))

    class Success(packet: ArtemisPacket, prevResult: ParseResult) : ParseResult(packet) {
        init {
            setPacketListeners(prevResult.interestedPacketListeners)
            setObjectListeners(prevResult.interestedObjectListeners)
        }
    }

    data class Fail(
        /**
         * Return any exception that occurred while parsing the packet. This
         * is only for non-fatal exceptions. A fatal exception (one occurring before
         * the payload can be read) should cause the exception to be thrown
         * instead.
         */
        val exception: ArtemisPacketException
    ) : ParseResult(exception.toUnknownPacket())

    private var interestedPacketListeners: List<ListenerFunction> = emptyList()
    private var interestedObjectListeners: List<ListenerFunction> = emptyList()

    /**
     * Adds ListenerMethods that are interested in the packet.
     */
    fun setPacketListeners(listeners: List<ListenerFunction>) {
        interestedPacketListeners = listeners
    }

    /**
     * Adds ListenerMethods that are interested in the objects in the packet.
     * (Applies only to ObjectUpdatePackets.)
     */
    fun setObjectListeners(listeners: List<ListenerFunction>) {
        interestedObjectListeners = listeners
    }

    /**
     * Convenience method for isInterestingPacket() || isInterestingObject().
     */
    val isInteresting: Boolean get() = isInterestingPacket || hasInterestingObject

    /**
     * Returns true if the packet was of interest to any listeners. Note that in
     * the case of an ObjectUpdatePacket, there may be listeners that aren't
     * interested in the packet itself, but are interested in certain types of
     * objects the packet may contain. Thus, it's entirely possible for
     * isInterestingPacket() to return false while isContainsInterestingObject()
     * returns true.
     */
    private val isInterestingPacket: Boolean get() = interestedPacketListeners.isNotEmpty()

    /**
     * Returns true if the packet is an ObjectUpdatePacket and it contains an
     * object of interest to one or more listeners.
     */
    private val hasInterestingObject: Boolean get() = interestedObjectListeners.isNotEmpty()

    /**
     * Fire the listeners that were interested in this packet or its contents.
     */
    fun fireListeners() {
        check(this !is Processing) { "Listeners cannot be fired before parsing attempt" }
        interestedPacketListeners.forEach { it.offer(packet) }
        if (packet is ObjectUpdatePacket) {
            packet.objects.forEach { obj -> interestedObjectListeners.forEach { it.offer(obj) } }
        }
    }
}
