# Dependabot Auto Merge
#
# This Action will automatically merge Pull Requests created by Dependabot.
name: 'Dependency review'
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-auto-merge:
    name: 'Auto merge Dependabot updates'
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true

