name: Reviewdog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 1 * * 2'
  workflow_dispatch:

permissions:
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Generate secret files
        if: github.event_name == 'pull_request'
        run: |
          echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 -d > ${{ github.workspace }}/keystore.properties
          echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d > ${{ github.workspace }}/app/google-services.json

      - name: Setup Detekt
        uses: peter-murray/setup-detekt@26449609a63e843a5b9bad8a4b63ef0ee717f7a5 # v3.0.0

      - name: Run Detekt
        continue-on-error: true
        run: |
          detekt-cli -i ${{ github.workspace }} -c ${{ github.workspace }}/config/detekt/detekt.yml \
          -r sarif:${{ github.workspace }}/detekt.sarif.json

      - name: Upload Detekt SARIF report to CodeQL
        uses: github/codeql-action/upload-sarif@f443b600d91635bebf5b0d9ebc620189c0d6fba5 # v4.30.8
        with:
          sarif_file: ${{ github.workspace }}/detekt.sarif.json
          checkout_path: ${{ github.workspace }}

      - name: Upload Detekt SARIF report to Reviewdog
        uses: HollowMan6/sarif4reviewdog@1dce5522fa5792a629d99ef000e474699a9a9b8e # v1.0.1
        with:
          file: ${{ github.workspace }}/detekt.sarif.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          bundler-cache: true

      - name: Run Rubocop
        uses: reviewdog/action-rubocop@fcb74ba274da10b18d038d0bcddaae3518739634 # v2.21.2
        with:
          only_changed: ${{ github.event_name == 'pull_request' }}
          rubocop_flags: -r code_scanning -f CodeScanning::SarifFormatter -o rubocop.sarif
          rubocop_version: gemfile
          skip_install: true
          use_bundler: true

      - name: Upload Rubocop SARIF report to CodeQL
        uses: github/codeql-action/upload-sarif@f443b600d91635bebf5b0d9ebc620189c0d6fba5 # v4.30.8
        with:
          sarif_file: ${{ github.workspace }}/rubocop.sarif
          checkout_path: ${{ github.workspace }}

  actions:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run actionlint
        uses: reviewdog/action-actionlint@f00ad0691526c10be4021a91b2510f0a769b14d0 # v1.68.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  android:
    name: Android Lint (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: app
            module: app
            category: android-lint
          - path: app/konsist
            module: app:konsist
            category: konsist
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Generate secret files
        run: |
          echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 -d > ${{ github.workspace }}/keystore.properties
          echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d > ${{ github.workspace }}/app/google-services.json

      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version-file: .tool-versions
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Android Lint
        uses: burrunan/gradle-cache-action@663fbad34e03c8f12b27f4999ac46e3d90f87eca # v3.0.1
        with:
          arguments: :${{ matrix.module }}:lint

      - name: Report to Reviewdog
        uses: DVDAndroid/action-android-lint@21c9fa6500c10caa12d8c581d9e280925f39510d # v1.2.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          lint_xml_file: ${{ matrix.path }}/build/reports/lint-results-debug.xml
          level: warning

      - name: Upload lint SARIF report to CodeQL
        uses: github/codeql-action/upload-sarif@f443b600d91635bebf5b0d9ebc620189c0d6fba5 # v4.30.8
        with:
          sarif_file: ${{ github.workspace }}/${{ matrix.path }}/build/reports/lint-results-debug.sarif
          checkout_path: ${{ github.workspace }}
          category: ${{ matrix.category }}

  protobuf:
    name: Protocol Buffers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run protolint
        uses: yoheimuta/action-protolint@e62319541dc5107df5e3a5010acb8987004d3d25 # v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
